[package]
name = "mh3se"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "linker=x86_64-w64-mingw32-gcc"]